remote_theme: pages-themes/minimal@v0.2.0
title: "Blake Grachek"
description: Multidisciplinary systems engineer based in Minneapolis
plugins:
- jekyll-remote-theme
github:
  is_user_page: false
title: "My Portfolio"
author: "Your Name"
description: "A collection of my technical projects."

# Navigation links (if supported by the theme)
header_pages:
  - index.md
  - projects.md  # This ensures "Projects" appears in the site navigation.
