remote_theme: pages-themes/cayman@v0.2.0

# Site Information
title: "Blake Grachek"
author: "Blake Grachek"
description: "Multidisciplinary systems engineer based in Minneapolis."

# Plugins
plugins:
  - jekyll-remote-theme

# GitHub Settings
github:
  is_user_page: false

# Navigation Links
header_pages:
  - index.md
  - projects.md  # Adds "Projects" to the site navigation
